/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class INScore_INScore */

#ifndef _Included_INScore_INScore
#define _Included_INScore_INScore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     INScore_INScore
 * Method:    GetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_INScore_INScore_GetVersion
  (JNIEnv *, jclass);

/*
 * Class:     INScore_INScore
 * Method:    GetJNIVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_INScore_INScore_GetJNIVersion
  (JNIEnv *, jclass);

/*
 * Class:     INScore_INScore
 * Method:    SetViewListener
 * Signature: (LINScore/ViewListener;)V
 */
JNIEXPORT void JNICALL Java_INScore_INScore_SetViewListener
  (JNIEnv *, jclass, jobject);

/*
 * Class:     INScore_INScore
 * Method:    GetBitmap
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_INScore_INScore_GetBitmap
  (JNIEnv *, jobject, jintArray, jint, jint);

/*
 * Class:     INScore_INScore
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_INScore_INScore_Init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
