#
# 
#

LIB := libmusicxml2.3.11.dylib

#===============================================================
libmusicxml2.dylib: $(LIB)
	ln -sf libmusicxml2.*.dylib libmusicxml2.dylib

#===============================================================
clean :
	rm -rf  libmusicxml2.dylib
