#!/bin/sh
#


count=$1
i=0

while [ $i -lt $count ]
do
	i=$(($i + 1))
	start=$(($i * 8))
	end=$((($i+1) * 8))
	for j in 1 2 3
	do
		echo /ITL/scene/cursor$j watch  \"timeEnter\" $start 1 $end 1 \"/ITL/scene/voix$j\" \"set\" \"img\" \"voix$j-$i.tiff\"
		echo /ITL/scene/cursor$j watch+ \"timeEnter\" $start 1 $end 1 \"/ITL/scene/voix$j\" \"mapf\" \"voix$j-$i.map\"
	done
done
