#!/bin/sh
#

if [ $# -ne 2 ]
then
	echo usage: shiftMap \"mapping file\" \"no de transposition\"
	echo exemple: \"shiftMap voix10.map 2\" pour la transposition 2
	exit 1
fi

file=$1
offset=$2

d1=$(($offset*8))
d2=$(($d1 + 1))
d3=$(($d2 + 1))
d4=$(($d3 + 1))
d5=$(($d4 + 1))
d6=$(($d5 + 1))
d7=$(($d6 + 1))
d8=$(($d7 + 1))
d9=$(($d8 + 1))

cat $file 	|   sed -e "s/\[0\/1/[$d1\/1/" \
			|   sed -e "s/\[1\/1/[$d2\/1/" \
			|   sed -e "s/, 1\/1/, $d2\/1/" \
			|   sed -e "s/\[2\/1/[$d3\/1/" \
			|   sed -e "s/, 2\/1/, $d3\/1/" \
			|   sed -e "s/\[3\/1/[$d4\/1/" \
			|   sed -e "s/, 3\/1/, $d4\/1/" \
			|   sed -e "s/\[4\/1/[$d5\/1/" \
			|   sed -e "s/, 4\/1/, $d5\/1/" \
			|   sed -e "s/\[5\/1/[$d6\/1/" \
			|   sed -e "s/, 5\/1/, $d6\/1/" \
			|   sed -e "s/\[6\/1/[$d7\/1/" \
			|   sed -e "s/, 6\/1/, $d7\/1/" \
			|   sed -e "s/\[7\/1/[$d8\/1/" \
			|   sed -e "s/, 7\/1/, $d8\/1/" \
			|   sed -e "s/, 8\/1/, $d9\/1/"

