#!/bin/sh
#

if [ $# -ne 1 ]
then
	echo usage: shiftAll \"nombre de transposition\"
	exit 1
fi

count=$1
i=0

while [ $i -lt $count ]
do
	i=$(($i + 1))
	for a in voix1 voix2 voix3
	do
		echo shiftMap ${a}0.map $i
		./shiftMap ${a}0.map $i > $a$i.map
	done
done
