#!/bin/sh
#
# extract the language definition from the lexer and parser
#

ydef=yacc.tex
tmpl=_tokens.txt

# first isolate the grammar
echo '\\begin{verbatim}' > $ydef
awk -f doc.awk ITL.y | sed -e 's/{..*//' | sed -e 's/	/    /g' >> $ydef
echo '\end{verbatim}' >> $ydef


# next get the tokens from the grammar
#for a in $(sed -e 's/[^A-Z 	]*//g' $ydef | grep [A-Z] | sed -e 's/[ 	][ 	]*/ /g')
for a in $(grep "%token" ITL.y | sed -e 's/%token//')
do
	echo $a 
done  | sort -u > $tmpl
