#!/bin/sh
#

TOOL=./INScoreViewer
#TOOL=./INScoreNOView

# --show-reachable=yes
#gen=--gen-suppressions=yes
gen=--gen-suppressions=all
ignore=--suppressions=valgrindignored.txt
#ignore=
valgrind --leak-check=full $ignore --show-reachable=no --log-file=check.out.txt $TOOL $*
