#!/bin/bash

if [ $# -ne 2 ]
then
	echo usage $0 file dest
	exit 1
fi

. ./wait.sh

path=/sdcard/inscore/scripts
file=$1
path2=/sdcard/inscore
dest=$path2/$2


echo inscore2pdf_android $file $dest
src=$(basename $file)
./SendOSC 192.168.1.133:7000 /ITL/scene rootPath $path/$(dirname $file)
./SendOSC 192.168.1.133:7000 /ITL/scene watch endPaint \( /ITL/scene export $dest \)
./SendOSC 192.168.1.133:7000 /ITL/scene load $src

sleep 1
