#!/bin/bash

if [ $# -ne 2 ]
then
	echo usage $0 file dest
	exit 1
fi

. ./wait.sh

path=$(pwd)
file=$1
dest=$path/$2


echo inscore2pdf $file $dest
src=$(basename $file)

./SendOSC 7000 /ITL/scene rootPath $path/$(dirname $file)
./SendOSC 7000 /ITL/scene watch endPaint \( /ITL/scene export $dest \)
./SendOSC 7000 /ITL/scene watch export \( /ITL/scene save $(pwd)/__tmp.inscore \)
./SendOSC 7000 /ITL/scene load $src

wait __tmp.inscore
rm -f __tmp.inscore

