#!/bin/bash

if [ $# -ne 5 ]
then
	echo usage $0 file dest remoteip localip device
	exit 1
fi

file=$1
remoteip=$3
localip=$4
device=$5

if [ "$device" = "android" ]
then
	root=/sdcard/inscore/
else
	#root=""
	root="/var/mobile/Applications/45EAB785-A7E0-4C57-954C-9D5ED7BB1988/Documents/"
fi

path=${root}scripts
dest=${root}$2

echo inscore2pdf_mobile $file $2 $remoteip $localip $device

src=$(basename $file)
./SendOSC $remoteip:7000 /ITL/scene rootPath $path/$(dirname $file)
./SendOSC $remoteip:7000 /ITL/scene watch endPaint \( /ITL/scene export $dest \)

# wait for a response at end of export
./SendOSC $remoteip:7000 /ITL/scene watch export \( $localip:7000/mobile end \)
gtimeout --preserve-status -s INT 5 ./ReceiveOSC -ip -c 2>/dev/null 1>/dev/null &
receivePid=$!

./SendOSC $remoteip:7000 /ITL/scene load $src
wait $receivePid
