#!/bin/sh

if [ $# -ne 2 ]
then
	echo usage $0 file dest
	exit 1
fi

../wait.sh

path=$(pwd)
file=$1
inscore=$path/$2


echo inscore2inscore $file $inscore
src=$(basename $file)

./SendOSC 7000 /ITL/scene rootPath $path/$(dirname $file)
./SendOSC 7000 /ITL/scene load $src
./SendOSC 7000 /ITL/scene save $inscore

wait $inscore

grep -v "/ITL guido-version" $inscore \
	| grep -v "/ITL musicxml-version" \
	| grep -v "/ITL ticks" \
	| grep -v "/ITL time" \
	| grep -v "/ITL/scene [xy]" \
	| grep -v "/ITL version" > tmp$$

mv -f tmp$$ $inscore
