#!/bin/sh

if [ $# -ne 2 ]
then
	echo usage $0 file dest
	exit 1
fi

. wait.sh

path=$(pwd)
file=$1
dest=$path/$2


echo inscore2log $file $dest
src=$(basename $file)

./SendOSC 7000 /ITL rootPath $path/$(dirname $file)
./SendOSC 7000 /ITL/scene rootPath $path/$(dirname $file)
./SendOSC 7000 /ITL/log clear
./SendOSC 7000 /ITL/scene load $src
./SendOSC 7000 /ITL/log save $dest

wait $dest

