#!/bin/sh

if [ $# -ne 2 ]
then
	echo usage $0 file dest
	exit 1
fi

function wait () {
	what=$1
	count=0
	while [ $count -lt 100000 ]
	do
		[ -f $what ] && break
		count=$(($count + 1))
	done
}

path=$(pwd)
file=$1
inscore=$path/$2


echo inscore2inscore $file $inscore
src=$(basename $file)

echo rootPath $path/$(dirname $file)
./SendOSC 7000 /ITL/scene rootPath $path/$(dirname $file)
./SendOSC 7000 /ITL/scene load $src
./SendOSC 7000 /ITL/scene save $inscore

wait $inscore

grep -v "/ITL guido-version" $inscore \
	| grep -v "/ITL musicxml-version" \
	| grep -v "/ITL ticks" \
	| grep -v "/ITL time" \
	| grep -v "/ITL version" > tmp$$

mv -f tmp$$ $inscore
