#!/bin/bash

if [ $# -ne 4 ]
then
	echo usage $0 file dest remoteip localip
	exit 1
fi

path=/sdcard/inscore/scripts
file=$1
path2=/sdcard/inscore
dest=$path2/$2
remoteip=$3
localip=$4

echo inscore2pdf_android $file $dest $remoteip $localip
src=$(basename $file)
./SendOSC $remoteip:7000 /ITL/scene rootPath $path/$(dirname $file)
./SendOSC $remoteip:7000 /ITL/scene watch endPaint \( /ITL/scene export $dest \)

# wait for a response at end of export
./SendOSC $remoteip:7000 /ITL/scene watch export \( $localip:7000/android end \)
timeout --preserve-status -s INT 5 ./ReceiveOSC -ip -c 2>/dev/null 1>/dev/null &
receivePid=$!

./SendOSC $remoteip:7000 /ITL/scene load $src

wait $receivePid

