#!/bin/sh

if [ $# -ne 2 ]
then
	echo usage $0 file dest
	exit 1
fi

function wait () {
	what=$1
	count=0
	while [ $count -lt 100000 ]
	do
		[ -f $what ] && break
		count=$(($count + 1))
	done
}

path=$(pwd)
file=$1
dest=$path/$2


echo inscore2pdf $file $dest
src=$(basename $file)

echo rootPath $path/$(dirname $file)
./SendOSC 7000 /ITL/scene rootPath $path/$(dirname $file)
./SendOSC 7000 /ITL/scene watch endPaint \( /ITL/scene export $dest \)
./SendOSC 7000 /ITL/scene watch export \( /ITL/scene save $(pwd)/__tmp.inscore \)
./SendOSC 7000 /ITL/scene load $src

wait __tmp.inscore
rm -f __tmp.inscore

