#!/bin/sh
#
# usage: maketar source destination
#        copy the content of source to destination
#        each source folder is copied as tar-gz archive
#

if [ $# -ne 2 ]
then
	cat << !
usage: maketar source destination
       copy the content of source to destination
       each source folder is copied as tar-gz archive
!
fi

DIR=$1
DST=$2
folders=$(find $DIR -type d -d 1)

[ -d $DST/$DIR ] || mkdir -p $DST/$DIR
cp -rf $DIR/* $DST/$DIR

cd $DST/$DIR
for a in $folders
do
	echo archiving $a
	arch=$(basename $a)
	tar czf $arch.tgz $arch
	rm -rf $arch
done
