#!/bin/sh
#

function usage() {
	echo "usage: $0 datafile [ time | model | view | update | total | localmap | graphicmap | all ]"
	exit 1
}


plotupdate="using 2 title \"model\", '' using 3 title \"localmap\", '' using 4 title \"gmap\", '' using 5 title \"view\""

plottime='using 1 title "time"'
plotmodel="using 2 title \"model\""
plotlmap="using 3 title \"localmap\""
plotgmap="using 4 title \"graphicmap\""
plotview="using 5 title \"view\""
plottotal="using 6 title \"total\""

all="using 1 title \"time\", '' using 2 title \"model\", '' using 3 title \"localmap\", '' using 4 title \"gmap\", '' using 5 title \"view\", '' using 6 title \"total\""

sum="using 1 title \"time\", '' using 6 title \"total\""

hist="set style data histogram; \
set style histogram rowstacked; \
set style fill solid border -1; \
set boxwidth 0.5; "


file=$1
style="set data style lines"
case $2 in
	"time") 	data=$plottime;;
	"model") 	data=$plotmodel;;
	"view") 	data=$plotview;;
	"update") 	data=$plotupdate;;
	"total") 	data=$plottotal;;
	"localmap") data=$plotlmap;;
	"graphicmap") 	data=$plotgmap;;
	"total") 	data=$plottotal;;
	"all") 		data=$all;;
	"sum") 		data=$sum;;
	*) usage
esac

case $# in
	3) 	range="set xrange [$3:]";;
	4) 	range="set xrange [$3:$4]";;
	*) 	range=""
esac

[ -n "$range" ] && [ "$data" == "$plotupdate" ] && style=$hist

size=$(wc -l $file)

cat << !
set title "$file"
set grid
$style
$range
plot '$file' $data
!
