# This is a basic workflow to help you get started with Actions

name: MacOS Deployment

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    environment: deployment

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - name: Install packages
        run: |
            bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
            brew install libmicrohttpd
            brew install git-lfs
            git lfs install

      - name: Build submodules
        run: make -C build modules

      - name: Build inscore
        run: make -C build inscore

      - name: Build inscore package
        run: make -C build package

      - name: Push package
        run: |
            git fetch origin library  --depth 1 --no-recurse-submodules
            echo PAT: $PAT
            cat version.txt
            make push ID=$GITHUB_RUN_ID BRANCH=library VERSION=$(cat version.txt)
            
